version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - artis3n
    assignees:
      - artis3n
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    reviewers:
      - artis3n
    assignees:
      - artis3n
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - artis3n
    assignees:
      - artis3n
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    reviewers:
      - artis3n
    assignees:
      - artis3n
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
