version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: '/'
    schedule:
      interval: monthly
    groups:
      all:
        patterns:
          - "*"
